services:
  app:
    #  build:
    #   context: .
    # image: lape
    image: ghcr.io/jhonatan1111/sistema-laboratorio-patologico:latest
    command: ["bash", "-lc", "php artisan migrate --force && php artisan db:seed --force || true; exec apache2-foreground"]
    ports:
      - "8080:80"
    profiles: ["dev"]
    volumes:
      - ./public/build:/var/www/html/public/build:ro
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:rbkwJFJA3z2Xq0cDjTamb1RHSErYrjV5RPT1bSak3E8=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: lape
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lape-network

  app-prod:
    image: ghcr.io/jhonatan1111/sistema-laboratorio-patologico:latest
    command: ["bash", "-lc", "php artisan migrate --force && php artisan db:seed --force || true; exec apache2-foreground"]
    ports:
      - "8080:80"
    profiles: ["prod"]
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:rbkwJFJA3z2Xq0cDjTamb1RHSErYrjV5RPT1bSak3E8=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: lape
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - lape-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lape
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - lape-network

networks:
  lape-network:
    driver: bridge

volumes:
  mysql-data:
